name: test

on:
  pull_request:
  push:

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - run: nix develop -c pytest -vvv
    - run: nix develop -c ruff check .
    - run: nix develop -c sh -c 'env PYTHONWARNINGS=ignore yapf -dr .'
    - run: nix build
    - run: nix flake check

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip3 install -U setuptools pip
      - run: pip3 install .[test]
      - run: pytest -vvv

  yapf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip3 install -U yapf
      - run: yapf -dr .

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
