name: test

on:
  pull_request:
  push:

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - run: nix develop -c pytest -vvv
    - run: nix develop -c ruff check .
    - run: nix develop -c ruff format --check .
    - run: nix build
    - run: nix flake check

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '{{ cookiecutter.min_python }}'
      - run: pip3 install -U setuptools pip
      - run: pip3 install .[test]
      - run: pytest -vvv

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1

  ruff-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          args: format --check .
