name: test

on:
  pull_request:
  push:

jobs:
  test-with-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: pip install cookiecutter
      - run: cookiecutter . --no-input -o /tmp/test project_name=ex_am-ple initial_year=2023
      - run: nix build -v /tmp/test/ex_am-ple
      - run: nix develop /tmp/test/ex_am-ple -c sh -c 'cd /tmp/test/ex_am-ple && pytest -vvv'
      - run: nix develop /tmp/test/ex_am-ple -c sh -c 'cd /tmp/test/ex_am-ple && ruff check .'
      - run: nix develop /tmp/test/ex_am-ple -c sh -c 'cd /tmp/test/ex_am-ple && ruff format --check .'
      - run: nix flake check /tmp/test/ex_am-ple --all-systems
      - run: nix run 'nixpkgs#actionlint' /tmp/test/ex_am-ple/.github/workflows/*.yml
      - run: nix run /tmp/test/ex_am-ple
      - run: cookiecutter . --no-input -o /tmp/test project_name=l_i-b initial_year=2023 kind=library
      - run: nix build -v /tmp/test/l_i-b
      - run: nix develop /tmp/test/l_i-b -c sh -c 'cd /tmp/test/l_i-b && pytest -vvv'
      - run: nix develop /tmp/test/l_i-b -c sh -c 'cd /tmp/test/l_i-b && ruff check .'
      - run: nix develop /tmp/test/l_i-b -c sh -c 'cd /tmp/test/l_i-b && ruff format --check .'
      - run: nix flake check /tmp/test/l_i-b --all-systems
      - run: nix run 'nixpkgs#actionlint' /tmp/test/l_i-b/.github/workflows/*.yml

  test-without-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - run: pip install -U setuptools pip
      - run: pip install cookiecutter
      - run: cookiecutter . --no-input -o /tmp/test project_name=ex_am-ple initial_year=2023
      - run: pip install '/tmp/test/ex_am-ple[test]'
      - run: sh -c 'cd /tmp/test/ex_am-ple && pytest -vvv'
      - run: sh -c 'cd /tmp/test/ex_am-ple && ruff check .'
      - run: sh -c 'cd /tmp/test/ex_am-ple && ruff format --check .'
      - run: ${{ steps.get_actionlint.outputs.executable }} /tmp/test/ex_am-ple/.github/workflows/*.yml
      - run: cookiecutter . --no-input -o /tmp/test project_name=l_i-b initial_year=2023 kind=library
      - run: pip install '/tmp/test/l_i-b[test]'
      - run: sh -c 'cd /tmp/test/l_i-b && pytest -vvv'
      - run: sh -c 'cd /tmp/test/l_i-b && ruff check .'
      - run: sh -c 'cd /tmp/test/l_i-b && ruff format --check .'
      - run: ${{ steps.get_actionlint.outputs.executable }} /tmp/test/l_i-b/.github/workflows/*.yml

  compare-against-reference:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install cookiecutter
      - run: cookiecutter . --no-input -o /tmp/test project_name=ex_am-ple initial_year=2023
      - run: cookiecutter . --no-input -o /tmp/test project_name=l_i-b initial_year=2023 kind=library
      - run: diff -ur reference /tmp/test
